- name: Playbook roles untuk semua
  hosts: googlevm
  become: true
  roles:
    # - { role: apt_basic, tags: "apt_basic_semua" }
    # - { role: users, tags: "user_create_semua" }
    # - { role: docker_install, tags: "docker_install_semua" }
    
    #  - { role: frontend_install, tags: "frontend_install_semua" }
     - { role: monitoring_install, tags: "monitoring_install_semua" }
