- name: Install python3-pip
  become: yes
  apt:
    name: python3-pip
    state: present
  when: ansible_os_family == "Debian"

- name: Install Docker Python module
  pip:
    name: docker
    state: present

- name: Pull Docker image from registry
  community.docker.docker_image:
    name: "{{ docker_image }}"
    source: pull

- name: Run docker container
  community.docker.docker_container:
    name: "{{ docker_container_name }}"
    image: "{{ docker_image }}"
    state: started
    restart_policy: "{{ docker_restart_policy }}"
    ports: "{{ docker_ports }}"
  notify: Restart Docker