- name: Update wajib apt 
  ansible.builtin.apt:
    update_cache: yes
  tags:
    - update

- name: Upgrade semua apt package 
  ansible.builtin.apt:
    upgrade: dist
  tags:
    - upgrade

- name: Install build-essential package 
  ansible.builtin.apt:
    name: "{{ essential_package }}"
    state: present
  tags:
    - install