- name: Include Docker tasks for Debian
  include_tasks: debian.yaml
  when: ansible_distribution == "Debian"

- name: Include Docker tasks for Ubuntu
  include_tasks: ubuntu.yaml
  when: ansible_distribution == "Ubuntu"