- name: "Update apt package cache"
  apt:
    update_cache: yes
    force_apt_get: yes

- name: "Upgrade all packages"
  apt:
    upgrade: dist
    force_apt_get: yes

- name: "Install dependencies"
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present

- name: "Add Docker GPG apt Key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: "Add Docker Repository"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes

- name: "Install Docker Engine"
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes

- name: "Start Docker service"
  service:
    name: docker
    state: started
    enabled: yes

- name: "Add new user to docker group"
  user:
    name: "ansible"
    groups: docker
    append: yes
